version: '2'
services:

  eureka-server:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  zuul-server:
    container_name: zuul-server
    build:
      context: zuul-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  account-server:
    container_name: account-server
    build:
      context: accountservice
      dockerfile: Dockerfile
    ports:
    - "9092:9092"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  node-server:
    container_name: node-server
    build:
      context: nodeservice
      dockerfile: Dockerfile
    ports:
    - "9091:9091"
    depends_on:
      - eureka-server
      - zuul-server
      - kafka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1